# Generated by Django 5.2.5 on 2025-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='per_day',
            field=models.BooleanField(default=False, help_text='Is this price per day?'),
        ),
    ]
