# Generated by Django 5.2.5 on 2025-10-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_item_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('accessories', 'Accessories'), ('gadgets', 'Gadgets'), ('books', 'Books'), ('sports', 'Sports Equipment'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
